### ISSUE TITLE
Support native R backends for rendering midi

### ISSUE THREAD

**Issue by jeroen** [urswilke/pyramidi#4]
The R packages [av](https://ropensci.r-universe.dev/av) (on cran) and [fluidsynth](https://ropensci.r-universe.dev/fluidsynth) (not yet on cran but soon) allow for synthesizing and converting audio without requiring the user to install any extra shell utilities. Perhaps supporting that back-end can lower the barrier to use pyramidi.

```r
install.packages(c('av', 'fluidsynth'), repos = 'https://ropensci.r-universe.dev')
```

Example use:

```r
midi <- system.file("extdata", "test_midi_file.mid", package = "pyramidi")
wav <- fluidsynth::midi_convert(midi, output = 'test.wav')
av::av_audio_convert("test.wav", "test.mp3")
```

**Comment by urswilke** [comment]
That's sooo awesome what you have done with fluidsynth! That will definitely lower the barrier to use pyramidi. I struggled so much when I first tried to make fluidsynth run on Linux some years ago... Nowadays it's much easier to install, but controlling it from R is just the cherry on top. And I also struggled so much back then to document the package, because for pkgdown I had to simulate the local rendering with fluidsynth installed by not evaluating code chunks and instead using hidden elements putting the resulting files where they would appear locally. It was awful. You're a true magician! Thank you very much

In the branch [refactor_synthing](https://github.com/urswilke/pyramidi/tree/refactor_synthing) I've now drafted a v0.2 to replace the dependency on the old helper package raudiomate with your packages. This is a complete rewriting of the synthetization and audio using these super cool possibilities in your packages. You can find the CHANGELOG [here](https://github.com/urswilke/pyramidi/blob/refactor_synthing/NEWS.md). This branch is also already the source of pyramidi’s [new pkgdown site](https://urswilke.github.io/pyramidi/).

@CrumpLab (I don’t know of any other users of this package... :) could you check if it breaks any functionality in your code and in particular your midiblender package? But I only touched the audio player/synthetization and as I understood, you couldn’t use these functionalities on your machine anyway. Then it should be fine and I would merge this branch to main soon. And I would also like to add a link to your blog and package in the [README](https://github.com/urswilke/pyramidi/tree/refactor_synthing?tab=readme-ov-file#pyramidi-out-in-the-wild) if that’s fine for you (and please don’t hesitate to correct my wording if something doesn’t sound right)

Thanks a lot for your help & feedback!

**Comment by CrumpLab** [comment]
Glad you are adding fluidsynth, and this merge shouldn't affect midiblender. Happy to be linked on the readme :) Thanks again for all your work on pyramidi!

**Comment by urswilke** [comment]
Thank you @CrumpLab! I merged it into main.

@jeroen Any chance you will also implement a midi write method in fluidsynth? Then the python dependencies in pyramidi  could also be replaced with R if I understand `fluidsynth::midi_read()` correctly.

**Comment by jeroen** [comment]
@urswilke yes we could try that, but I think that is a bit more complicated, because we need to validate and trigger each row in the data frame to a corresponding midi event. But I think it can certainly be done. I'm still toying with `midi_read()` not sure if I have the best approach to implement this.

**Comment by jeroen** [comment]
FYI the first version of fluidsynth is now on CRAN so you can depend om it easier.

Not sure if you followed the other conversation, but we ended up using `av::av_audio_convert` inside fluidsynth to convert the audio to the desired output format so you no longer need to do this manually.  Just `midi_read()` or `midi_convert()` will automatically do the encoding as well.

**Comment by urswilke** [comment]
@jeroen Please excuse the late reply! (my computer crashed multiple times and I've lost the drafts I had already written...). Thanks for the hint that `av::av_audio_convert()` is now used in fluidsynth! I completely missed that. I could now drop the av dependency from pyramidi in the latest release.

I quite like the dataframe format that `fluidsynth::midi_read()` produces. AFAIU it's close to the midi format. 

Regarding the writing of midi files, I realized that in libfluidsynth this functionality doesn't exist either. Would be really interested how you would tackle this - if you had in mind to write this functionality completely in R or use another external library... I'd love, for instance, to contribute some validation checks or something like that, if it could be of any help. But I think I won't find a lot of time to work on this in the near future and probably you could do it faster without me. And I'm not sad if this still takes time, because I think once you can write midi files directly from R, it won't take long that somebody comes up with something much better than pyramidi... :)

Anyways, I will close this issue now. Once more, thank you very much for your packages and opening this issue!

@CrumpLab You might want to make sure that in midiblender you don't rely too much on the weird formats in pyramidi (for the case that writing midi files from R is possible one day)...
